"""skill-projects — the Projects tool family over the gateway ``/projects`` API.

Spec: ``project-docs/specs/projects_ai_chat.md``.

``__all__`` is the tool surface. The declarative builder
(``orchestrator/declarative.py``) reads it, and
``tests/unit/test_projects_chat_coverage.py`` holds it against
``manifest.py``: every exported name is a manifest tool, and every manifest
tool that is not exported is in ``manifest.PLANNED`` with its slice.
"""

from skill_projects.forms import edit_project, edit_task, propose_plan
from skill_projects.guarded import (
    archive_project,
    archive_task,
    bulk_update,
    delete_attachment,
    delete_comment,
    delete_field,
    delete_status,
    delete_tag,
    delete_type,
    delete_view,
    merge_tags,
    merge_tasks,
    move_project,
    report_delete,
    revert_activity,
    set_status_set,
    unarchive_project,
)
from skill_projects.inbox import (
    calendar,
    capture_intake,
    intake_queue,
    mark_notifications_read,
    my_contexts,
    my_led_projects,
    notifications,
    project_access,
    project_views,
    save_view,
    triage_intake,
    watchers,
)
from skill_projects.nav import open_in_app
from skill_projects.reads import (
    analytics_finished,
    analytics_load,
    analytics_outlook,
    analytics_stuck,
    analytics_throughput,
    find_conflicts,
    find_tasks,
    fit_for_task,
    list_tasks,
    my_task,
    my_work,
    people_for,
    project_summary,
    projects_tree,
    rebalance,
    recurrence,
    report_list,
    report_render,
    task_dataset,
    task_detail,
    team_capacity,
    vocabulary,
)
from skill_projects.views import (
    render_board,
    render_report,
    render_tasks,
    render_timeline,
    status_report,
)
from skill_projects.writes import (
    add_subtasks,
    assign,
    comment,
    complete,
    create_field,
    create_personal_task,
    create_project,
    create_status,
    create_tag,
    create_task,
    create_type,
    defer,
    edit_comment,
    link_tasks,
    move_task,
    report_save,
    set_my_overlay,
    set_recurrence,
    unarchive_task,
    unlink_tasks,
    update_field,
    update_project,
    update_status,
    update_tag,
    update_task,
    update_type,
    watch,
)

__all__ = [  # noqa: RUF022 — grouped by class, which is the reader's question
    # Class A — reads (S1)
    "analytics_finished",
    "analytics_load",
    "analytics_outlook",
    "analytics_stuck",
    "analytics_throughput",
    "find_tasks",
    "list_tasks",
    "my_work",
    "people_for",
    "project_summary",
    "projects_tree",
    "report_list",
    "report_render",
    "task_detail",
    "vocabulary",
    # Class A — the two reads S2b needed
    "my_task",
    "recurrence",
    # Class A — the views: reads that draw a card (S4)
    "render_board",
    "render_report",
    "render_tasks",
    "render_timeline",
    "status_report",
    # Class A — the rest of the reads (S5)
    "calendar",
    "intake_queue",
    "my_contexts",
    # Class A — WS-39 S6e, the projects I lead
    "my_led_projects",
    "notifications",
    "project_access",
    "project_views",
    "watchers",
    # Class A — navigation (S6)
    "open_in_app",
    # Class A — team intelligence (S7a capacity, S7b fit and rebalancing,
    # S7c conflicts, S7e on-the-fly analysis)
    "team_capacity",
    "fit_for_task",
    "rebalance",
    "find_conflicts",
    "task_dataset",
    # Class B — reversible writes, one card each (S2)
    "add_subtasks",
    "assign",
    "comment",
    "complete",
    "create_project",
    "create_task",
    "defer",
    "link_tasks",
    "move_task",
    "report_save",
    "unarchive_task",
    "unlink_tasks",
    "update_project",
    "update_task",
    "watch",
    # Class B — the rest: vocabulary, a comment of one's own, the repeat
    # rule, the private capture and the overlay (S2b)
    "create_field",
    "create_personal_task",
    "create_status",
    "create_tag",
    "create_type",
    "edit_comment",
    "set_my_overlay",
    "set_recurrence",
    "update_field",
    "update_status",
    "update_tag",
    "update_type",
    # Class B — the forms: an editable card, then the class B card (S4)
    "edit_project",
    "edit_task",
    "propose_plan",
    # Class B — the rest of the writes (S5)
    "capture_intake",
    "mark_notifications_read",
    "save_view",
    "triage_intake",
    # Class C — hard to undo, one act one card, the impact first (S3)
    "archive_project",
    "archive_task",
    "bulk_update",
    "delete_attachment",
    "delete_comment",
    "delete_field",
    "delete_status",
    "delete_tag",
    "delete_type",
    "delete_view",
    "merge_tags",
    "merge_tasks",
    "move_project",
    "report_delete",
    "revert_activity",
    "set_status_set",
    "unarchive_project",
]
