/**
 * POST /api/agent/chat
 *
 * Returns a Server-Sent Events stream so the UI can render tokens and
 * tool-call events in real time (mirroring the VS Code Copilot experience).
 *
 * IMPORTANT — Three distinct runtimes; do not conflate:
 *
 *   mode="copilot"   → GitHub Copilot SDK runtime (apps/services/gateway/gateway/routes/copilot_chat.py)
 *                       - CopilotClient wraps `gh copilot` CLI as a subprocess
 *                       - autopilot mode: native tool-calling (shell, file r/w, Python)
 *                       - reads AGENTS.md / .mcp.json from agent workspace
 *                       - on_pre_tool_use / on_post_tool_use hooks emit tool_start/tool_end SSE
 *                       - Auth: GITHUB_TOKEN (direct to api.githubcopilot.com)
 *                              OR BYOK via LiteLLM (session_kwargs["provider"])
 *                       - NOT the same as CopilotKit (the React UI library)
 *
 *   mode="litellm"   → Direct LiteLLM streaming (no orchestration, no tool calling)
 *                       - Raw OpenAI-compatible /chat/completions call
 *                       - Model = tier1/2/3 alias in infra/litellm/config.yaml
 *                       - Used for fast text-only responses
 *
 *   mode="langgraph" → Legacy LangGraph agent runner (batch, no streaming)
 *                       - POST /agent/run on FastAPI gateway
 *                       - Returns single delta+done pair (not streamed)
 *                       - Future: replace with /agent/langgraph streaming endpoint
 *
 * SSE event types:
 *   {"type":"delta",      "content":"…"}
 *   {"type":"reasoning",  "content":"…"}              — model chain-of-thought (reasoning models only)
 *   {"type":"progress",   "name":"…"}                  — tool about to run (live status)
 *   {"type":"tool_start", "id":"…","name":"…","args":{}}
 *   {"type":"tool_end",   "id":"…","name":"…","result":"…","success":bool}
 *   {"type":"done",       "run_id":"…"}
 *   {"type":"error",      "content":"…"}
 */

import { NextRequest, NextResponse } from "next/server";
import { auth, isAuthEnabled } from "@/auth";
import { GATEWAY_URL, gatewayHeaders, requireIdentity } from "@/lib/gateway";
import {
  foldForToolStart,
  unfoldTrailingAnswer,
  groupReasoningBlocks,
  serializeReasoning,
} from "@/lib/chatStream";

export const runtime = "nodejs";
export const dynamic = "force-dynamic";

export interface ChatMessage {
  role: "user" | "assistant" | "system";
  content: string;
}

interface ChatRequest {
  agentName: string;
  message: string;
  messages: ChatMessage[];
  threadId: string;
  mode?: "langgraph" | "copilot" | "litellm";
  /** Copilot SDK model override forwarded to gateway (e.g. "claude-sonnet-4.5"). */
  model?: string;
  /** System-level context (persistent memory / persona) injected as context. */
  context?: string;
  /** Thinking mode: "auto" | "thinking" | "max" */
  thinkMode?: string;
  /** Assistant message ID generated by the frontend.  Used so server-side
   *  persistence writes to the SAME row the frontend renders, enabling
   *  reliable refresh recovery. */
  assistantMessageId?: string;
  /** Last SSE event ID the client received before disconnecting.  Sent on
   *  reconnect so the server can replay only missed events. */
  lastEventId?: string;
  /** When true, the client is reconnecting to an existing agent run rather
   *  than starting a new one.  The route calls the reconnect endpoint. */
  reconnect?: boolean;
}

const LITELLM_BASE_URL =
  process.env.COPILOT_LLM_BASE_URL ?? process.env.LITELLM_BASE_URL ?? "http://127.0.0.1:8080/v1";
const LITELLM_KEY =
  process.env.LITELLM_MASTER_KEY ?? "";

/**
 * Save the accumulated assistant message to Postgres so it survives client
 * disconnect (tab close, browser quit, network drop). Called periodically
 * during streaming and once when the stream completes.
 *
 * Persists content, tool events, reasoning blocks, and progress lines so
 * the polling recovery path can restore the full stream state (thinking
 * cascade, tool progress, etc.) — not just the final text.
 */
async function persistAssistantMessage(
  threadId: string,
  content: string,
  toolEvents: Array<Record<string, unknown>> = [],
  reasoningBlocks: string[] = [],
  progressLines: string[] = [],
  messageId?: string,
  todos: Array<{ id: string; title: string; status: string }> = [],
  customEvents: Array<{ name: string; value: unknown }> = [],
  segments: Array<{ id: string; text: string }> = [],
): Promise<void> {
  if (!content.trim() && toolEvents.length === 0 && reasoningBlocks.length === 0 && todos.length === 0 && customEvents.length === 0) return;
  try {
    // Pack todos + segments (Phase 3b) into agent_state — no dedicated columns.
    const agentState: Record<string, unknown> = {};
    if (todos.length > 0) agentState.todos = todos;
    if (segments.length > 0) agentState.segments = segments;
    const payload = [{
      // The caller always supplies a message ID (frontend-provided, or a
      // per-stream fallback minted in translateAndPersistStream).  The old
      // shared `assistant-${threadId}` fallback upserted every assistant turn
      // of the thread onto ONE row, silently overwriting prior turns.
      id: messageId || `assistant-${threadId}-${Date.now().toString(36)}`,
      role: "assistant",
      content,
      timestamp: Date.now(),
      tool_events: toolEvents,
      progress_lines: progressLines,
      reasoning: serializeReasoning(reasoningBlocks),
      // Carry the structured todo list + real message segments in agent_state
      // so the Todos panel and 3b segment-native rendering survive a refresh
      // (no dedicated DB columns needed).
      agent_state: Object.keys(agentState).length > 0 ? agentState : null,
      custom_events: customEvents,
    }];
    // Write directly to the gateway's chat message store so messages survive
    // even if the Next.js process restarts mid-stream.
    await fetch(
      `${GATEWAY_URL}/chat/sessions/${threadId}/messages`,
      {
        method: "POST",
        headers: await gatewayHeaders({ "Content-Type": "application/json" }),
        body: JSON.stringify(payload),
        signal: AbortSignal.timeout(5000),
      }
    );
  } catch {
    // Best-effort: don't break the stream for persistence failures
  }
}

/**
 * Translate AG-UI events from the backend into our SSE format, persisting
 * the accumulated assistant message to Postgres along the way so the
 * conversation survives client disconnects.
 *
 * Returns the accumulated assistant content for final persistence.
 */
async function translateAndPersistStream(
  agUiBody: ReadableStream<Uint8Array>,
  controller: ReadableStreamDefaultController<Uint8Array>,
  threadId: string,
  assistantMessageId?: string,
): Promise<string> {
  // Stable per-STREAM persistence id: when the frontend didn't supply one,
  // mint it once here — per-call minting would write a new row on every 3s
  // checkpoint, and the old per-thread constant collapsed all turns into one.
  const persistId =
    assistantMessageId || `assistant-${threadId}-${Date.now().toString(36)}`;
  const reader = agUiBody.getReader();
  const decoder = new TextDecoder();
  const toolNames: Record<string, string> = {};
  const toolArgs: Record<string, string> = {};
  /** Reasoning-block count at each tool's start — persisted as
   *  reasoningCutoff so the UI can interleave reasoning and tools
   *  chronologically (VS Code-style timeline). */
  const toolCutoffs: Record<string, number> = {};
  /** Segment count at each tool's start — persisted as segmentCutoff (Phase 3b)
   *  so a reloaded message interleaves real segments with tools chronologically.
   *  Only recorded for id-carrying runs; absent for id-less streams. */
  const toolSegCutoffs: Record<string, number> = {};
  /** Real assistant-message segments (Phase 3a/3b), one per TEXT_MESSAGE_START/
   *  END pair the runtime emitted, in order. Ground truth for narration-vs-
   *  answer; persisted in agent_state.segments. Empty for id-less runtimes. */
  const segments: Array<{ id: string; text: string }> = [];
  const segmentAppend = (msgId: string, delta: string) => {
    const seg = segments.find((s) => s.id === msgId);
    if (seg) seg.text += delta;
    else segments.push({ id: msgId, text: delta });
  };
  const toolStarts: Record<string, number> = {};
  const toolEvents: Array<Record<string, unknown>> = [];
  /** Accumulated reasoning blocks (model chain-of-thought).  Each complete
   *  sentence / paragraph becomes a separate block for the UI cascade. */
  const reasoningBlocks: string[] = [];
  /** Brief progress snippets shown in the ThinkingContainer header. */
  const progressLines: string[] = [];
  /** Artifact and other custom events (artifact_created, etc.) — persisted
   *  so ArtifactCard components survive page refresh. */
  const customEvents: Array<{ name: string; value: unknown }> = [];
  /** Latest structured todo-list snapshot (persisted via agent_state). */
  let latestTodos: Array<{ id: string; title: string; status: string }> = [];
  /** Sub-agent (delegation) activity accumulated since the last delegate tool
   *  ended — attached to that tool's persisted event at TOOL_CALL_END so the
   *  nested timeline survives a page refresh (it previously existed only in
   *  the frontend's live loop and was lost on reload).  Mirrors the ToolEvent
   *  subAgent* fields the frontend renders. */
  let subAgent: {
    name: string;
    text: string;
    tools: Array<{ id: string; name: string; status: string; result?: string }>;
  } = { name: "", text: "", tools: [] };
  let buf = "";
  let assistantContent = "";
  /** Index in reasoningBlocks of the most recently folded answer (visible text
   *  moved into the timeline at a tool_start).  Un-folded back into
   *  assistantContent at RUN_FINISHED when no answer text followed the last tool
   *  call.  -1 = nothing to un-fold.  Mirror of unfoldTrailingAnswer() in
   *  hooks/useAgentChat.ts. */
  let foldedAnswerIdx = -1;
  let lastPersistTime = Date.now();
  let clientConnected = true;

  /** Safely enqueue to the client; sets clientConnected=false on failure. */
  const enqueue = (data: Record<string, unknown>) => {
    if (!clientConnected) return;
    try {
      controller.enqueue(
        new TextEncoder().encode(`data: ${JSON.stringify(data)}\n\n`)
      );
    } catch {
      clientConnected = false;
    }
  };

  try {
    while (true) {
      const { done, value } = await reader.read();
      if (done) break;
      buf += decoder.decode(value, { stream: true });
      const lines = buf.split("\n");
      buf = lines.pop() ?? "";
      for (const line of lines) {
        if (!line.startsWith("data: ")) continue;
        const raw = line.slice(6).trim();
        if (!raw) continue;
        let ev: Record<string, unknown>;
        try { ev = JSON.parse(raw); } catch { continue; }
        const t = ev.type as string;
        let out: Record<string, unknown> | null = null;

        if (t === "TEXT_MESSAGE_CONTENT") {
          const delta = String(ev.delta ?? "");
          assistantContent += delta;
          // New visible answer text → any earlier fold was genuine narration.
          // Only REAL text counts (mirror of chatStream.ts): stray whitespace
          // deltas around tool boundaries must not cancel the trailing un-fold,
          // or the persisted answer ends up inside the reasoning timeline.
          if (delta.trim()) foldedAnswerIdx = -1;
          // messageId rides along (Phase 3a): the backend now emits REAL
          // per-segment message ids, so the client can track segment
          // boundaries instead of inferring them from tool positions.
          const segId = typeof ev.messageId === "string" ? ev.messageId : "";
          if (segId) segmentAppend(segId, delta);
          out = { type: "delta", content: delta, messageId: ev.messageId };
        } else if (t === "TEXT_MESSAGE_START") {
          const segId = typeof ev.messageId === "string" ? ev.messageId : "";
          if (segId && !segments.some((s) => s.id === segId)) {
            segments.push({ id: segId, text: "" });
          }
          out = { type: "message_start", messageId: ev.messageId };
        } else if (t === "TEXT_MESSAGE_END") {
          out = { type: "message_end", messageId: ev.messageId };
        } else if (t === "REASONING_MESSAGE_CONTENT" || t === "THINKING_TEXT_MESSAGE_CONTENT") {
          const chunk = String(ev.delta ?? "");
          if (chunk) {
            // Paragraph-grouped reasoning blocks (shared with the frontend
            // cascade via groupReasoningBlocks).
            reasoningBlocks.splice(
              0,
              reasoningBlocks.length,
              ...groupReasoningBlocks(reasoningBlocks, chunk),
            );
          }
          out = { type: "reasoning", content: ev.delta ?? "" };
        } else if (t === "PROGRESS_UPDATE") {
          // Tool progress / partial output — shown in the thinking header,
          // never in the visible assistant message.
          const msg = String(ev.message ?? "");
          if (msg) {
            progressLines.push(msg);
            if (progressLines.length > 20) progressLines.shift();
          }
          out = { type: "progress", name: msg };
        } else if (t === "TODO_LIST") {
          // Structured todo list (VS Code Todos panel parity).
          const todoItems = (ev.todos ?? []) as Array<{ id: string; title: string; status: string }>;
          latestTodos = todoItems;
          out = { type: "todos", todos: todoItems };
        } else if (t === "TOOL_CALL_START") {
          const name = String(ev.toolCallName ?? ev.tool_call_name ?? "tool");
          toolNames[String(ev.toolCallId ?? "")] = name;
          toolArgs[String(ev.toolCallId ?? "")] = "";
          // VS Code-style narration fold (shared with the frontend via
          // foldForToolStart): text accumulated before a tool call is plan
          // narration, not the answer — fold it into the reasoning timeline and
          // record where this tool sits so reasoning interleaves chronologically.
          //
          // Phase 3b: mirror chatStream.ts — when the runtime supplied real
          // segment ids, segments already own every piece of assistant text, so
          // do NOT fold narration into reasoningBlocks (that would duplicate it).
          // Still clear assistantContent so a stale pre-tool narration doesn't
          // linger; reasoningBlocks then holds only genuine chain-of-thought.
          const hasSegments = segments.length > 0;
          const narration = assistantContent.trim();
          const folded = hasSegments
            ? { blocks: reasoningBlocks, cutoff: reasoningBlocks.length }
            : foldForToolStart(reasoningBlocks, narration);
          if (!hasSegments) {
            reasoningBlocks.splice(0, reasoningBlocks.length, ...folded.blocks);
          }
          toolCutoffs[String(ev.toolCallId ?? "")] = folded.cutoff;
          if (hasSegments) {
            toolSegCutoffs[String(ev.toolCallId ?? "")] = segments.length;
          }
          if (narration) {
            // Remember where the folded answer landed so RUN_FINISHED can
            // restore it if the turn ends on a tool call (no answer follows).
            // With segments the last-segment rescue handles this instead.
            if (!hasSegments) foldedAnswerIdx = folded.cutoff - 1;
            assistantContent = "";
          }
          toolStarts[String(ev.toolCallId ?? "")] = Date.now();
          // Capture progress so the polling recovery path can show tool activity.
          progressLines.push(name);
          if (progressLines.length > 20) progressLines.shift();
          enqueue({ type: "progress", name });
          out = { type: "tool_start", id: ev.toolCallId, name, args: {} };
        } else if (t === "TOOL_CALL_ARGS") {
          const id = String(ev.toolCallId ?? "");
          toolArgs[id] = (toolArgs[id] ?? "") + String(ev.delta ?? "");
        } else if (t === "TOOL_CALL_PARTIAL") {
          // Live terminal/tool output for a running tool — forward to the
          // client so output streams into the tool row (VS Code style).
          out = {
            type: "tool_partial",
            id: ev.toolCallId,
            result: String(ev.delta ?? ev.content ?? ""),
          };
        } else if (t === "TOOL_CALL_END" || t === "TOOL_CALL_RESULT") {
          const id = String(ev.toolCallId ?? "");
          const name = toolNames[id] ?? "tool";
          const result = String(ev.result ?? ev.content ?? "");
          // Attach the nested delegation timeline accumulated since the last
          // delegate ended (SUB_AGENT_* events stream BETWEEN the delegate
          // tool's start and end).  Same shape the frontend live loop builds.
          const isDelegate = name.toLowerCase().includes("call_agent");
          const subAgentFields = isDelegate && (subAgent.name || subAgent.text || subAgent.tools.length > 0)
            ? { subAgentName: subAgent.name, subAgentText: subAgent.text, subAgentTools: subAgent.tools }
            : {};
          if (isDelegate) subAgent = { name: "", text: "", tools: [] };
          toolEvents.push({
            id, name,
            args: parseToolArgs(toolArgs[id]),
            result,
            // Persist the REAL outcome — hardcoding "done" made failed tools
            // render as succeeded after a reload (the forwarded live event
            // below already honoured ev.success).
            status: ev.success !== false ? "done" : "error",
            reasoningCutoff: toolCutoffs[id] ?? 0,
            // Only for id-carrying runs (Phase 3b) — omitted otherwise so
            // id-less rows keep the pre-3b tool-event shape.
            ...(id in toolSegCutoffs ? { segmentCutoff: toolSegCutoffs[id] } : {}),
            startedAt: toolStarts[id],
            endedAt: Date.now(),
            ...subAgentFields,
          });
          out = {
            type: "tool_end", id: ev.toolCallId, name,
            args: parseToolArgs(toolArgs[id]),
            // Honour the backend's success flag (TOOL_CALL_RESULT carries
            // success=_exc is None). Treat a missing flag as success for
            // backward compatibility (TOOL_CALL_END may omit it). Mirrors the
            // sub-agent path below and the live reducer in chatStream.ts.
            result, success: ev.success !== false,
          };
        } else if (t === "STATE_SNAPSHOT") {
          out = { type: "state", snapshot: ev.snapshot ?? {} };
        } else if (t === "STATE_DELTA") {
          out = { type: "state_delta", delta: ev.delta ?? [] };
        } else if (t === "CUSTOM") {
          const cev = { name: String(ev.name ?? ""), value: ev.value ?? null };
          customEvents.push(cev);
          out = { type: "custom", name: cev.name, value: cev.value };
        } else if (t === "SUB_AGENT_TEXT_DELTA") {
          const agent = String(ev.agentName ?? "");
          subAgent.name = subAgent.name || agent;
          subAgent.text += String(ev.delta ?? "");
          out = { type: "sub_agent_delta", agentName: agent, runId: String(ev.runId ?? ""), delta: String(ev.delta ?? "") };
        } else if (t === "SUB_AGENT_TOOL_CALL_START") {
          const agent = String(ev.agentName ?? "");
          const stId = String(ev.toolCallId ?? "");
          subAgent.name = subAgent.name || agent;
          subAgent.tools.push({ id: stId, name: String(ev.toolCallName ?? "tool"), status: "running" });
          out = { type: "sub_agent_tool_start", agentName: agent, id: stId, name: String(ev.toolCallName ?? "") };
        } else if (t === "SUB_AGENT_TOOL_CALL_RESULT") {
          const stId = String(ev.toolCallId ?? "");
          const ok = ev.success !== false;
          const st = subAgent.tools.find((x) => x.id === stId);
          if (st) { st.result = String(ev.content ?? ""); st.status = ok ? "done" : "error"; }
          out = { type: "sub_agent_tool_end", agentName: String(ev.agentName ?? ""), id: stId, result: String(ev.content ?? ""), success: ok };
        } else if (t === "SUB_AGENT_ERROR") {
          subAgent.text += subAgent.text ? `\n[error] ${String(ev.error ?? "Sub-agent error")}` : `[error] ${String(ev.error ?? "Sub-agent error")}`;
          out = { type: "sub_agent_error", agentName: String(ev.agentName ?? ""), error: String(ev.error ?? "Sub-agent error") };
        } else if (t === "RUN_FINISHED" || t === "done") {
          // RUN_FINISHED: standard AG-UI event from the agent executor.
          // "done": synthetic event from the reconnect endpoint when the
          // agent has already finished (Redis stream expired or empty).
          // Un-fold a trailing answer: when the turn ended on a tool call
          // (save_memory, manage_todo_list, write_artifact, …) the genuine
          // answer was folded into the timeline and assistantContent is empty.
          // Restore it so the persisted message (refresh recovery + memory
          // extraction) carries the answer instead of an empty bubble.  Shared
          // with the frontend via unfoldTrailingAnswer.
          const unfolded = unfoldTrailingAnswer(assistantContent, reasoningBlocks, foldedAnswerIdx);
          assistantContent = unfolded.content;
          if (unfolded.reasoningBlocks && unfolded.reasoningBlocks !== reasoningBlocks) {
            reasoningBlocks.splice(0, reasoningBlocks.length, ...unfolded.reasoningBlocks);
          }
          // Segment ground truth (Phase 3c — VS Code parity): when the runtime
          // emitted real segments, EVERY assistant text segment is answer body,
          // not just the last — assistant text emitted before a tool call is
          // answer content, not thinking-pane narration. `content` is the full
          // answer = all non-empty segments joined (matching the renderer's
          // answerBody and chat_fold.py's fold so both persisters agree). Blank
          // any segment text the tool-boundary fold stranded in reasoning so it
          // isn't shown twice.
          if (segments.length > 0) {
            const segTexts = segments.map((s) => s.text).filter((t) => t.trim());
            const joined = segTexts.join("\n\n");
            if (joined.trim()) {
              for (const st of segTexts) {
                for (let i = reasoningBlocks.length - 1; i >= 0; i--) {
                  if (reasoningBlocks[i].trim() === st.trim()) {
                    reasoningBlocks[i] = "";
                    break;
                  }
                }
              }
              assistantContent = joined;
            }
          }
          out = { type: "done", run_id: ev.runId || ev.run_id };
        } else if (t === "RUN_ERROR") {
          out = { type: "error", content: String(ev.message ?? "Agent run error") };
        }

        // Forward the Redis stream ID so the frontend can track the last
        // event it received — enables precise reconnection after disconnect.
        if (out && ev._stream_id) {
          out._stream_id = ev._stream_id;
        }

        if (out) enqueue(out);

        // Persist every 3s while streaming, so messages survive client disconnect.
        // Include reasoning blocks and progress lines so the polling recovery
        // path can restore the full stream state (thinking cascade, tool
        // progress, etc.) — not just the final text.
        const now = Date.now();
        if ((assistantContent.trim() || reasoningBlocks.length > 0 || latestTodos.length > 0 || customEvents.length > 0) && now - lastPersistTime > 3000) {
          lastPersistTime = now;
          persistAssistantMessage(threadId, assistantContent, toolEvents, reasoningBlocks, progressLines, persistId, latestTodos, customEvents, segments).catch(() => {});
        }
      }
    }
  } catch {
    // Backend stream ended early
  }

  // Final persist — ensure the complete message is saved with all stream metadata.
  if (assistantContent.trim() || toolEvents.length > 0 || reasoningBlocks.length > 0 || latestTodos.length > 0 || customEvents.length > 0) {
    await persistAssistantMessage(threadId, assistantContent, toolEvents, reasoningBlocks, progressLines, persistId, latestTodos, customEvents, segments).catch(() => {});
  }

  if (clientConnected) {
    try { controller.close(); } catch { /* already closed */ }
  }

  return assistantContent;
}

// ─── Memory extraction (post-stream) ─────────────────────────────────────────

// Memory extraction is no longer done here.  Both orchestrator paths
// (/copilot/chat and /agent/run/stream) now extract at the gateway's RUN
// BOUNDARY (core_loop_unification P1-9): it fires on finish/error/cancel/
// reconnect even when this reader is gone, and folds in the assistant answer —
// which a client-side, reader-lifetime-bound extraction could never guarantee.
// The old client-side extractMemories() was removed to avoid double extraction.

/**
 * Headers for gateway proxy calls, as the signed-in member.
 *
 * This used to fall back to "internal-only headers (backward-compatible with
 * cron/CI callers)" when there was no session — which the gateway reads as the
 * platform acting as itself, i.e. every permission. A browser request with no
 * session took that branch. `lib/gateway.ts` now throws instead; see the note
 * there for why omitting an identity has to fail closed.
 */
async function buildGatewayHeaders(): Promise<Record<string, string>> {
  return gatewayHeaders({ "Content-Type": "application/json" });
}

// ─── SSE helpers ─────────────────────────────────────────────────────────────

function sseHeaders(): HeadersInit {
  return {
    "Content-Type": "text/event-stream",
    "Cache-Control": "no-cache, no-transform",
    Connection: "keep-alive",
    "X-Accel-Buffering": "no",
  };
}

function sseEvent(payload: Record<string, unknown>): Uint8Array {
  return new TextEncoder().encode(`data: ${JSON.stringify(payload)}\n\n`);
}

/** Parse an accumulated AG-UI tool-args JSON string into an object for the UI. */
function parseToolArgs(raw: string | undefined): Record<string, unknown> {
  if (!raw || !raw.trim()) return {};
  try {
    const parsed = JSON.parse(raw);
    return typeof parsed === "object" && parsed !== null
      ? (parsed as Record<string, unknown>)
      : { value: parsed };
  } catch (_e) {
    // Streamed args may be incomplete/non-JSON — surface the raw text.
    return { _raw: raw };
  }
}

// ─── Route handler ────────────────────────────────────────────────────────────

/**
 * Drop a trailing history entry that duplicates the current user turn.
 *
 * Current clients exclude the just-sent turn from `messages`, but older
 * clients (and any external caller) may still include it AND send it as
 * `message` — the model then sees the prompt twice.  The litellm path always
 * deduped; this makes the copilot and executor paths equally safe.
 */
function withoutCurrentTurn(
  history: Array<{ role: string; content: string }>,
  message: string,
): Array<{ role: string; content: string }> {
  const last = history[history.length - 1];
  return last && last.role === "user" && last.content === message
    ? history.slice(0, -1)
    : history;
}

export async function POST(req: NextRequest): Promise<Response> {
  const me = await requireIdentity();
  if (me instanceof NextResponse) return me;
  let body: ChatRequest;
  try {
    body = (await req.json()) as ChatRequest;
  } catch (_e) {
    return new Response(
      `data: ${JSON.stringify({ type: "error", content: "Invalid JSON body" })}\n\n`,
      { status: 400, headers: sseHeaders() }
    );
  }

  const { agentName, message, messages, threadId, mode, model, context, thinkMode, assistantMessageId, lastEventId, reconnect } = body;
  if (!agentName || !message) {
    return new Response(
      `data: ${JSON.stringify({ type: "error", content: "agentName and message are required" })}\n\n`,
      { status: 400, headers: sseHeaders() }
    );
  }

  // ── Require authentication (middleware marks /api/agent as public, so the
  //    route must gate itself).  Skipped when auth is disabled (dev). ──
  let userId = "";
  try {
    const session = await auth();
    userId = session?.user?.email ?? "";
    if (isAuthEnabled && !userId) {
      return new Response(
        `data: ${JSON.stringify({ type: "error", content: "Unauthorized" })}\n\n`,
        { status: 401, headers: sseHeaders() }
      );
    }
  } catch { /* non-request context — extraction will be skipped */ }

  // ── Reconnect path: resume an existing agent stream after disconnect ────
  // When the frontend detects an interrupted stream on mount, it sends
  // reconnect=true with the last known event ID.  The gateway replays
  // missed events from Redis and continues with live events if the agent
  // is still running.
  if (reconnect && threadId) {
    const since = lastEventId || "0-0";
    let reconRes: Response;
    try {
      reconRes = await fetch(
        `${GATEWAY_URL}/agent/run/${encodeURIComponent(threadId)}/reconnect?since=${encodeURIComponent(since)}`,
        {
          method: "GET",
          headers: await buildGatewayHeaders(),
          signal: AbortSignal.timeout(310_000),
        },
      );
    } catch (err) {
      const msg = err instanceof Error ? err.message : String(err);
      return new Response(
        `data: ${JSON.stringify({ type: "error", content: `Reconnect failed: ${msg}` })}\n\n`,
        { status: 502, headers: sseHeaders() },
      );
    }
    if (!reconRes.ok || !reconRes.body) {
      const text = await reconRes.text().catch(() => `status ${reconRes.status}`);
      return new Response(
        `data: ${JSON.stringify({ type: "error", content: `Reconnect error: ${text}` })}\n\n`,
        { status: reconRes.status, headers: sseHeaders() },
      );
    }
    // Pass the reconnect stream through the same translation layer so the
    // frontend sees the same event format as a live stream.
    const reconStream = new ReadableStream<Uint8Array>({
      async start(controller) {
        await translateAndPersistStream(
          reconRes.body!, controller, threadId, assistantMessageId,
        );
      },
    });
    return new Response(reconStream, { headers: sseHeaders() });
  }

  // ── Gateway /v1 path: stream directly via litellm SDK ────────────────────
  // Routes to LiteLLM tier aliases (tier1/2/3 are cost-optimized tiers).
  // Backend can optionally route tiers through Copilot, Claude, GPT-4, or Gemini
  // (see infra/litellm/config.yaml for current routing).
  if (mode === "litellm") {
    return streamLiteLLM({ message, messages, model, context });
  }

  // ── Copilot/AG-UI path — ORCHESTRATOR ONLY ────────────────────────────────
  // The /copilot/chat endpoint is hardwired at gateway startup to the single
  // built-in orchestrator agent. Named agents (task-manager, sales-assistant,
  // any GitHub-registered agent) must go through /agent/run so the executor
  // can clone the repo, import agents.py, resolve integrations, and run via MAF.
  // The orchestrator is now a REGISTERED agent (gateway _AGENT_REGISTRY), so it
  // runs through /agent/run/stream like every other one — same executor, same
  // permission handler, same memory injection. These aliases are what the UI
  // and stored sessions can carry for it; normalise them to the registered slug
  // so the named-agent path resolves instead of 422-ing.
  // (agent_architecture.md §11.1.1 — retires the /copilot/chat branch.)
  const ORCHESTRATOR_ALIASES = new Set(["orchestrator", "default", "metorite", ""]);
  const resolvedAgentName = ORCHESTRATOR_ALIASES.has(agentName.toLowerCase().trim())
    ? "orchestrator"
    : agentName;

  // ── Executor path: named agents (copilot mode) + langgraph mode ──────────
  // Named agents (copilot mode): route through /agent/run/stream which returns
  // a real AG-UI SSE stream so the UI sees tool events live.
  // Legacy langgraph mode: falls back to batch /agent/run (no streaming).
  if (mode === "copilot") {
    // /agent/run/stream returns the same AG-UI event format as /copilot/chat.
    let streamRes: Response;
    try {
      streamRes = await fetch(`${GATEWAY_URL}/agent/run/stream`, {
        method: "POST",
        headers: await buildGatewayHeaders(),
        body: JSON.stringify({
          agent: resolvedAgentName,
          payload: {
            mode: "chat", message,
            messages: withoutCurrentTurn(
              (messages ?? []).map((m) => ({ role: m.role, content: m.content })),
              message,
            ),
            think_mode: thinkMode ?? "auto",
            // Forward the caller's system context (persona / persistent memory /
            // app-specific context like the email app's selected account + open
            // email) so named agents — not just the orchestrator — receive it.
            // The executor injects it as a leading system message.
            ...(context ? { system_context: context } : {}),
          },
          thread_id: threadId ?? undefined,
          model: model ?? undefined,
          // Same row id the translator below checkpoints: the gateway's
          // authoritative fold-and-persist at run end (P0-3) upserts it, so
          // the tail survives even if this reader is gone.
          assistant_message_id: assistantMessageId ?? undefined,
        }),
        signal: AbortSignal.timeout(310_000),
      });
    } catch (err) {
      const msg = err instanceof Error ? err.message : String(err);
      return new Response(
        `data: ${JSON.stringify({ type: "error", content: `Gateway unreachable: ${msg}` })}\n\n`,
        { status: 502, headers: sseHeaders() }
      );
    }
    // The second caller stands down (docs/multiplayer/README.md §4.6). When the
    // gateway folded this message into a run that was already going it answers
    // 202 with `{steered: true}` and NO stream — because the turn that is
    // already running owns the answer. Passing the JSON through verbatim (not
    // translating it into an SSE frame) is what keeps this surface from
    // rendering a second assistant message: delivering from both sides is how
    // one answer gets posted twice.
    if (streamRes.status === 202) {
      const body = await streamRes.text().catch(() => "{}");
      return new Response(body, {
        status: 202,
        headers: { "Content-Type": "application/json" },
      });
    }
    if (!streamRes.ok || !streamRes.body) {
      const text = await streamRes.text().catch(() => `status ${streamRes.status}`);
      return new Response(
        `data: ${JSON.stringify({ type: "error", content: text })}\n\n`,
        { status: streamRes.status, headers: sseHeaders() }
      );
    }
    // Translate AG-UI → frontend SSE, persisting to Postgres so messages
    // survive client disconnect (tab close, browser quit, network drop).
    // Memory extraction for this path is OWNED BY THE GATEWAY at the run
    // boundary (P1-9): it fires even when this reader is gone, and firing
    // here too would double-extract every turn.
    const translated2 = new ReadableStream<Uint8Array>({
      async start(controller) {
        await translateAndPersistStream(
          streamRes.body!, controller, threadId ?? "", assistantMessageId,
        );
      },
    });
    return new Response(translated2, { headers: sseHeaders() });
  }

  // ── Legacy executor path: batch /agent/run (langgraph mode + fallback) ─
  // Used for langgraph mode. Returns a single delta+done SSE pair.
  const stream = new ReadableStream<Uint8Array>({
    async start(controller) {
      try {
        const gatewayRes = await fetch(`${GATEWAY_URL}/agent/run`, {
          method: "POST",
          headers: await buildGatewayHeaders(),
          body: JSON.stringify({
            agent: agentName,
            payload: {
              mode: "chat", message,
              messages: withoutCurrentTurn(
                (messages ?? []).map((m) => ({ role: m.role, content: m.content })),
                message,
              ),
            },
            thread_id: threadId ?? undefined,
          }),
          signal: AbortSignal.timeout(310_000),
        });

        if (!gatewayRes.ok) {
          const text = await gatewayRes.text().catch(() => `status ${gatewayRes.status}`);
          controller.enqueue(sseEvent({ type: "error", content: `Gateway error: ${text}` }));
          controller.close();
          return;
        }

        const data = (await gatewayRes.json()) as {
          run_id: string;
          agent: string;
          status: string;
          result?: unknown;
          error?: string;
          mutation_pr?: string;
        };

        // Normalise to string
        let content: string;
        if (data.status === "failed") {
          content = data.error
            ? `Agent run failed: ${data.error}${data.mutation_pr ? `\n\nA fix PR has been opened: ${data.mutation_pr}` : ""}`
            : "Agent run failed with an unknown error.";
        } else if (typeof data.result === "string") {
          content = data.result;
        } else if (data.result && typeof data.result === "object" && "content" in (data.result as object)) {
          content = String((data.result as { content: unknown }).content);
        } else {
          content = JSON.stringify(data.result, null, 2);
        }

        // Strip integration setup tokens before emitting
        const setupTokenRegex = /<<<SETUP:([^:]+):([A-Z0-9_]+)=([^>]+)>>>/g;
        const rawMatches: Array<{ service: string; key: string; value: string }> = [];
        let m: RegExpExecArray | null;
        while ((m = setupTokenRegex.exec(content)) !== null) {
          rawMatches.push({ service: m[1], key: m[2], value: m[3].trim() });
        }
        if (rawMatches.length > 0) {
          content = content.replace(/<<<SETUP:[^>]+>>>/g, "").trim();
          const vars = rawMatches.filter((x) => x.value).map((x) => ({ key: x.key, value: x.value }));
          if (vars.length > 0) {
            fetch(`${GATEWAY_URL}/integrations/configure`, {
              method: "POST",
              headers: await buildGatewayHeaders(),
              body: JSON.stringify({ vars }),
            }).catch(() => {});
          }
        }

        controller.enqueue(sseEvent({ type: "delta", content }));
        controller.enqueue(sseEvent({ type: "done", run_id: data.run_id }));
      } catch (err) {
        const msg = err instanceof Error ? err.message : String(err);
        controller.enqueue(sseEvent({ type: "error", content: msg }));
      } finally {
        controller.close();
      }
    },
  });

  return new Response(stream, { headers: sseHeaders() });
}

// ─── Gateway /v1 streaming (litellm SDK) ─────────────────────────────────────
// Streams an OpenAI-compatible chat completion from the gateway /v1 and
// re-emits it in our SSE format (delta / done / error). Enables the unified
// chat window to use any LiteLLM model alias (tier1/2/3, copilot/*).

function streamLiteLLM({
  message,
  messages,
  model,
  context,
}: {
  message: string;
  messages: ChatMessage[];
  model?: string;
  context?: string;
}): Response {
  const stream = new ReadableStream<Uint8Array>({
    async start(controller) {
      try {
        const history = (messages ?? [])
          .filter((m) => m.role === "user" || m.role === "assistant")
          .map((m) => ({ role: m.role, content: m.content }));

        const chatMessages: { role: string; content: string }[] = [];
        if (context?.trim()) {
          chatMessages.push({
            role: "system",
            content: context.trim(),
          });
        }
        // history already includes the current user turn (appended client-side),
        // but guard against the last entry not being the current message.
        const hasCurrent =
          history.length > 0 &&
          history[history.length - 1].role === "user" &&
          history[history.length - 1].content === message;
        chatMessages.push(...history);
        if (!hasCurrent) chatMessages.push({ role: "user", content: message });

        const upstream = await fetch(`${LITELLM_BASE_URL}/chat/completions`, {
          method: "POST",
          headers: {
            "Content-Type": "application/json",
            Authorization: `Bearer ${LITELLM_KEY}`,
          },
          body: JSON.stringify({
            model: model ?? "tier2-sonnet",
            messages: chatMessages,
            stream: true,
          }),
          signal: AbortSignal.timeout(310_000),
        });

        if (!upstream.ok || !upstream.body) {
          const text = await upstream.text().catch(() => `status ${upstream.status}`);
          controller.enqueue(sseEvent({ type: "error", content: `LiteLLM error: ${text}` }));
          controller.close();
          return;
        }

        const reader = upstream.body.getReader();
        const decoder = new TextDecoder();
        let buffer = "";

        while (true) {
          const { done, value } = await reader.read();
          if (done) break;
          buffer += decoder.decode(value, { stream: true });
          const lines = buffer.split("\n");
          buffer = lines.pop() ?? "";
          for (const line of lines) {
            const trimmed = line.trim();
            if (!trimmed.startsWith("data:")) continue;
            const raw = trimmed.slice(5).trim();
            if (!raw || raw === "[DONE]") continue;
            try {
              const json = JSON.parse(raw) as {
                choices?: {
                  delta?: {
                    content?: string;
                    // Reasoning / chain-of-thought fields used by thinking models:
                    //   • Gemini 2.5 thinking — "reasoning_content"
                    //   • Claude extended thinking (via LiteLLM) — "thinking_content"
                    //   • Some providers use "thinking"
                    reasoning_content?: string;
                    thinking_content?: string;
                    thinking?: string;
                  };
                }[];
              };
              const delta = json.choices?.[0]?.delta;
              if (!delta) continue;
              if (delta.content) {
                controller.enqueue(sseEvent({ type: "delta", content: delta.content }));
              }
              // Emit reasoning tokens so ThinkingContainer can show chain-of-thought.
              const reasoningDelta =
                delta.reasoning_content ?? delta.thinking_content ?? delta.thinking;
              if (reasoningDelta) {
                controller.enqueue(sseEvent({ type: "reasoning", content: reasoningDelta }));
              }
            } catch (_e) {
              // ignore non-JSON keep-alive lines
            }
          }
        }

        controller.enqueue(sseEvent({ type: "done" }));
      } catch (err) {
        const msg = err instanceof Error ? err.message : String(err);
        controller.enqueue(sseEvent({ type: "error", content: `LiteLLM unreachable: ${msg}` }));
      } finally {
        controller.close();
      }
    },
  });

  return new Response(stream, { headers: sseHeaders() });
}
